import type { Metadata } from "next";
import { montserrat } from "@/config/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="es" className="scroll-smooth dark" suppressHydrationWarning>
      <body
        className={`${montserrat.className} flex min-h-screen flex-col bg-background text-foreground antialiased barberia-dark`}
      >
        {children}
        {modal}
      </body>
    </html>
  );
}
